// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO3TTfMLPcPqjDJVjNvarkVnih8QNRkyM',
    appId: '1:199949700124:web:5d69f1145d042376fba3d9',
    messagingSenderId: '199949700124',
    projectId: 'booking-app-e8cba',
    authDomain: 'booking-app-e8cba.firebaseapp.com',
    storageBucket: 'booking-app-e8cba.firebasestorage.app',
    measurementId: 'G-ZQPV2D6KXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkAL4G0R9_crfxfIrFKpIPbhwddXSgCjk',
    appId: '1:199949700124:android:44816008f2397a1cfba3d9',
    messagingSenderId: '199949700124',
    projectId: 'booking-app-e8cba',
    storageBucket: 'booking-app-e8cba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp14o7O1cTh3kNblABoJ6SvKTPcqmgNN4',
    appId: '1:199949700124:ios:358b030f0b37577ffba3d9',
    messagingSenderId: '199949700124',
    projectId: 'booking-app-e8cba',
    storageBucket: 'booking-app-e8cba.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp14o7O1cTh3kNblABoJ6SvKTPcqmgNN4',
    appId: '1:199949700124:ios:358b030f0b37577ffba3d9',
    messagingSenderId: '199949700124',
    projectId: 'booking-app-e8cba',
    storageBucket: 'booking-app-e8cba.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO3TTfMLPcPqjDJVjNvarkVnih8QNRkyM',
    appId: '1:199949700124:web:550e3994a378cd37fba3d9',
    messagingSenderId: '199949700124',
    projectId: 'booking-app-e8cba',
    authDomain: 'booking-app-e8cba.firebaseapp.com',
    storageBucket: 'booking-app-e8cba.firebasestorage.app',
    measurementId: 'G-ZG3MYPHCW1',
  );
}
